version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "6433:1433"
    environment:
      SA_PASSWORD: "Rafael@123"
      ACCEPT_EULA: "Y"
